# -*- coding: utf-8 -*-
"""
Structured Data with Exact Page Numbers for:
1. Table of Contents / Index
2. List of Figures
3. List of Tables
All entries have right-aligned tab stops and dot leaders.
Strictly restructured to the required 10 academic chapters and subtopics.
Calibrated exactly against the compiled master academic project report PDF.
"""

TOC_ITEMS = [
    # (level, title, page)
    (0, "Preliminary Pages", "i"),
    (1, "Title Page", "i"),
    (1, "Certificate of Authenticity", "ii"),
    (1, "Candidate Declaration", "iii"),
    (1, "Acknowledgement", "iv"),
    (1, "Abstract", "v"),
    (1, "Table of Contents / Index", "vi"),
    (1, "List of Figures", "viii"),
    (1, "List of Tables", "ix"),
    (1, "List of Abbreviations", "x"),
    (0, "Chapter 1 — Problem Identification & Feasibility Study", "1"),
    (1, "1.1 Identification of a Real-World Problem", "1"),
    (1, "1.2 Problem Justification and Scope Definition", "1"),
    (1, "1.3 Stakeholder Identification", "3"),
    (1, "1.4 Feasibility Analysis", "4"),
    (0, "Chapter 2 — Requirement Engineering", "5"),
    (1, "2.1 Functional Requirements Specification", "5"),
    (1, "2.2 Non-Functional Requirements", "8"),
    (1, "2.3 Use Case Analysis and Actor Profiles", "9"),
    (1, "2.4 Requirement Prioritization – MoSCoW", "10"),
    (1, "2.5 Constraints and Assumptions", "10"),
    (0, "Chapter 3 — SDLC Planning", "12"),
    (1, "3.1 Selection of SDLC Model", "12"),
    (1, "3.2 Work Breakdown Structure (WBS)", "13"),
    (1, "3.3 Project Timeline / Gantt Chart", "13"),
    (1, "3.4 Resource Planning", "14"),
    (0, "Chapter 4 — System Modeling Using UML", "15"),
    (1, "4.1 Event Table", "15"),
    (1, "4.2 Use Case Diagram", "17"),
    (1, "4.3 Class Diagram", "18"),
    (1, "4.4 Sequence Diagram", "19"),
    (1, "4.5 Activity Diagram", "20"),
    (1, "4.6 Entity-Relationship Diagram", "22"),
    (1, "4.7 Deployment Diagram", "23"),
    (0, "Chapter 5 — System Architecture Design", "24"),
    (1, "5.1 Overall System Architecture", "25"),
    (1, "5.2 Frontend Architecture and Prototype", "26"),
    (1, "5.3 Prototype–Architecture Mapping", "38"),
    (1, "5.4 Backend Architecture", "39"),
    (1, "5.5 Database Schema Design", "41"),
    (1, "5.6 Security Considerations", "49"),
    (0, "Chapter 6 — Application Development", "49"),
    (1, "6.1 Frontend Implementation", "49"),
    (1, "6.2 Backend Implementation", "63"),
    (1, "6.3 Database Integration", "63"),
    (1, "6.4 Authentication & Validation", "63"),
    (1, "6.5 Error Handling", "64"),
    (0, "Chapter 7 — Integration & System Testing", "64"),
    (1, "7.1 Unit Testing", "64"),
    (1, "7.2 Black-Box Testing", "65"),
    (1, "7.3 Integration Testing", "66"),
    (1, "7.4 Test Case Preparation", "67"),
    (1, "7.5 Bug Tracking", "72"),
    (0, "Chapter 8 — Deployment", "73"),
    (1, "8.1 Hosting / Deployment", "73"),
    (1, "8.2 Responsive or Mobile Deployment", "73"),
    (1, "8.3 Server Configuration", "74"),
    (1, "8.4 Version Control Using GitHub", "74"),
    (0, "Chapter 9 — Performance & Security Testing", "78"),
    (1, "9.1 Load Testing", "78"),
    (1, "9.2 Input Validation Checks", "82"),
    (1, "9.3 Security Validation", "83"),
    (0, "Chapter 10 — Result and Discussion", "86"),
    (1, "10.1 Project Results", "86"),
    (1, "10.2 Objective vs Implementation", "87"),
    (1, "10.3 Actual Application Screenshots", "88"),
    (1, "10.4 User Manual", "88"),
    (1, "10.5 Source Code Documentation", "89"),
    (1, "10.6 Limitations and Future Scope", "90"),
    (1, "10.7 Conclusion", "91"),
]

FIGURE_ITEMS = [
    ("Figure 3.1: Project Gantt Chart (Sem-V 2026-27 Milestones & Timeline)", "14"),
    ("Figure 4.1: UML Event Table — System Triggers, Sources, and Responses", "16"),
    ("Figure 4.2: UrbanClean Use Case Diagram — Actors, Use Cases, and System Boundary", "17"),
    ("Figure 4.3: UrbanClean UML Class Diagram", "18"),
    ("Figure 4.4: UML Sequence Diagram — End-to-End Complaint Lifecycle", "19"),
    ("Figure 4.5: UrbanClean Activity Diagram — Complaint Processing, Routing, and Resolution Flow", "21"),
    ("Figure 4.6: Entity-Relationship Diagram of UrbanClean", "22"),
    ("Figure 4.7: UrbanClean Deployment Diagram", "24"),
    ("Figure 5.1: UrbanClean Public Landing Page Prototype", "27"),
    ("Figure 5.2: UrbanClean Multi-Role Unified Authentication Portal Prototype", "28"),
    ("Figure 5.3: UrbanClean Citizen Registration Prototype", "29"),
    ("Figure 5.4: UrbanClean Citizen Waste Reporting Prototype", "30"),
    ("Figure 5.5: UrbanClean Interactive Location Selection and GPS Map Prototype", "31"),
    ("Figure 5.6: UrbanClean Citizen Complaint Tracking Prototype", "32"),
    ("Figure 5.7: UrbanClean Waste Collection Driver Dashboard Prototype", "33"),
    ("Figure 5.8: UrbanClean Driver TSP Route Optimization Prototype", "34"),
    ("Figure 5.9: UrbanClean Proof-of-Cleanup Upload Verification Prototype", "35"),
    ("Figure 5.10: UrbanClean Municipal Administrator Dashboard Prototype", "36"),
    ("Figure 5.11: UrbanClean City-Wide Waste Monitoring and GIS Map Prototype", "37"),
    ("Figure 5.12: UrbanClean Monthly Compliance Tracking and Data Export Prototype", "38"),
    ("Figure 5.13: UrbanClean Backend Structure and Data Flow Diagram", "39"),
    ("Figure 5.14: DB Browser for SQLite — accounts & complaints Tables", "45"),
    ("Figure 5.15: DB Browser for SQLite — driver_routes & notifications Tables", "47"),
    ("Figure 5.16: DB Browser for SQLite — drivers Fleet Roster Table", "49"),
    ("Figure 6.1: Public Landing Page, Multi-Role Login & Citizen Registration Views", "51"),
    ("Figure 6.2: Citizen Waste Reporting Interface & Interactive Map Pinning Views", "53"),
    ("Figure 6.3: GPS Geolocation Telemetry, Citizen Ticket Tracking & Driver Dashboard Views", "55"),
    ("Figure 6.4: Driver Optimized Route Map (5 Stops) & Proof-of-Cleanup Upload Views", "57"),
    ("Figure 6.5: Municipal Administrator Command Center, Active Drivers & Daily Complaints Modal Views", "59"),
    ("Figure 6.6: City-Wide Waste Monitoring Map & Monthly Compliance Tracking Report with Excel Export Views", "61"),
    ("Figure 6.7: Mobile Responsive Device View across Smartphone Viewport Views", "63"),
    ("Figure 7.1: Unit Testing Suite Execution Output (unit_tests.js — S23)", "65"),
    ("Figure 7.2: REST API & Component Integration Verification (integration_tests.js — S24)", "66"),
    ("Figure 7.3: Dual Persistence (db.json <-> SQLite) Sync Verification (verify_db_sync.py — S25)", "67"),
    ("Figure 8.1: GitHub Repository Remote & Branch Configuration (S44)", "75"),
    ("Figure 8.2: GitHub Project Directory Structure (git ls-tree — S45)", "76"),
    ("Figure 8.3: Source Code Tracking & Working Tree Commit Inspection (git log -n 1 --stat — S46)", "77"),
    ("Figure 8.4: Git Commit History Timeline & Provenance Audit (git log --graph --oneline — S47)", "78"),
    ("Figure 9.1: Autocannon Basic Load Testing Configuration (S37)", "79"),
    ("Figure 9.2: Autocannon Live Concurrency Load Execution Progress (S38)", "80"),
    ("Figure 9.3: Autocannon Concurrency Load Test Final Results (S39)", "81"),
    ("Figure 9.4: REST API Response Time & Latency Benchmark (benchmark_latency.js — S36)", "82"),
    ("Figure 9.5: Input Validation Failure — Duplicate Account & Password Constraints (S30)", "83"),
    ("Figure 9.6: Cryptographic Session Authentication — POST /api/login (S32)", "84"),
    ("Figure 9.7: Defect BUG-01: Raw 500 Stack Trace on Invalid File MIME Upload (S40)", "85"),
    ("Figure 9.8: Defect BUG-01 Retest: Graceful HTTP 400 Bad Request JSON Response (S41)", "86"),
]

TABLE_ITEMS = [
    ("Table 1.1: Stakeholder Identification and System Expectations", "3"),
    ("Table 2.1: Functional Requirements Specification (FR-01 to FR-28)", "5"),
    ("Table 2.2: Non-Functional Requirements Specification (NFR-01 to NFR-19)", "8"),
    ("Table 2.3: Hardware Requirements Specification", "11"),
    ("Table 2.4: Software Technology Stack Specifications", "11"),
    ("Table 3.1: Work Breakdown Structure (WBS)", "13"),
    ("Table 3.2: Project Milestone Schedule (Project Gantt Chart Sem-V 2026-27)", "14"),
    ("Table 5.1: Prototype–Architecture Mapping", "38"),
    ("Table 5.2: Data Dictionary — accounts Table", "41"),
    ("Table 5.3: Data Dictionary — complaints Table", "41"),
    ("Table 5.4: Data Dictionary — driver_routes Table", "42"),
    ("Table 5.5: Data Dictionary — drivers Table", "42"),
    ("Table 5.6: Data Dictionary — notifications Table", "43"),
    ("Table 7.1: Master Software Testing Test Case Log (TC-01 through TC-52)", "67"),
    ("Table 7.2: Test Cases Category Breakdown and Execution Metrics", "72"),
    ("Table 10.1: Evaluated Operational Fuel Savings Across Municipal Fleets", "86"),
    ("Table 10.2: Comparison of Project Objectives with Implementation Results", "87"),
]
