# -*- coding: utf-8 -*-
"""
Structured Data with Exact Page Numbers for:
1. Table of Contents / Index
2. List of Figures
3. List of Tables
All entries have right-aligned tab stops and dot leaders.
"""

TOC_ITEMS = [
    # (level, title, page)
    # level 0: Major section / chapter (bold, left indent 0.0)
    # level 1: Section (regular, left indent 0.25)
    # level 2: Subsection (regular, left indent 0.45)
    (0, "Preliminary Pages", "i"),
    (1, "Title Page", "i"),
    (1, "Certificate of Authenticity", "ii"),
    (1, "Candidate Declaration", "iii"),
    (1, "Acknowledgement", "iv"),
    (1, "Abstract", "v"),
    (1, "Table of Contents / Index", "vi"),
    (1, "List of Figures", "ix"),
    (1, "List of Tables", "x"),
    (1, "List of Abbreviations", "xi"),
    (0, "Chapter 1 — Problem Identification & Feasibility Study", "1"),
    (1, "1.1 Introduction", "1"),
    (1, "1.2 Background of the Project", "1"),
    (1, "1.3 Problem Identification", "1"),
    (1, "1.4 Problem Statement", "2"),
    (1, "1.5 Existing System", "2"),
    (1, "1.6 Limitations of Existing System", "2"),
    (1, "1.7 Proposed System", "3"),
    (1, "1.8 Objectives of UrbanClean", "3"),
    (1, "1.9 Scope of the Project", "4"),
    (1, "1.10 Stakeholder Identification", "4"),
    (1, "1.11 Target Users", "4"),
    (1, "1.12 Feasibility Study", "5"),
    (1, "1.13 Project Constraints", "6"),
    (1, "1.14 Assumptions", "6"),
    (1, "1.15 Expected Outcomes", "6"),
    (0, "Chapter 2 — Requirement Engineering", "6"),
    (1, "2.1 Introduction", "7"),
    (1, "2.2 Requirement Gathering", "7"),
    (1, "2.3 Stakeholder Requirements", "7"),
    (1, "2.4 Functional Requirements (FR-01 to FR-28)", "7"),
    (1, "2.5 Non-Functional Requirements (NFR-01 to NFR-19)", "10"),
    (1, "2.6 User Requirements", "12"),
    (1, "2.7 System Requirements", "12"),
    (1, "2.8 Use-Case Analysis Across Actors", "12"),
    (1, "2.9 Requirement Prioritization (MoSCoW Framework)", "13"),
    (1, "2.10 Project Constraints & Assumptions", "13"),
    (1, "2.11 Hardware Requirements", "13"),
    (1, "2.12 Software Requirements", "14"),
    (0, "Chapter 3 — Software Development Life Cycle (SDLC) Planning", "15"),
    (1, "3.1 Introduction & SDLC Philosophy", "15"),
    (1, "3.2 Selected SDLC Model (Iterative Agile)", "15"),
    (1, "3.3 Reason for Selecting the SDLC Model", "15"),
    (1, "3.4 SDLC Phases & Milestones", "15"),
    (1, "3.5 Work Breakdown Structure (WBS)", "16"),
    (1, "3.6 Project Activities Deconstruction", "17"),
    (1, "3.7 Project Timeline & Milestone Schedule", "17"),
    (1, "3.8 Resource Planning (Human, Software, Hardware)", "18"),
    (1, "3.9 Risk Identification, Assessment, and Mitigation", "18"),
    (1, "3.10 Project Gantt Chart (Sem-V 2026-27)", "19"),
    (0, "Chapter 4 — System Modeling Using UML", "19"),
    (1, "4.1 Introduction & UML Overview", "19"),
    (1, "4.2 Actors of the System & Privilege Boundaries", "19"),
    (1, "4.3 UML Event Table", "20"),
    (1, "4.4 Class Diagram", "22"),
    (1, "4.5 Object Diagram (Runtime Snapshot)", "23"),
    (1, "4.6 Use Case Diagram", "24"),
    (1, "4.7 Sequence Diagram — End-to-End Complaint Lifecycle", "25"),
    (1, "4.8 Component Diagram", "27"),
    (1, "4.9 Deployment Diagram", "28"),
    (1, "4.10 Activity Diagram — Operational Logic", "29"),
    (0, "Chapter 5 — System Architecture Design", "31"),
    (1, "5.1 Introduction & Overall System Architecture", "31"),
    (1, "5.2 Frontend Architecture & Client State Model", "32"),
    (1, "5.3 Backend Architecture & RESTful Pipeline", "33"),
    (2, "5.3.1 Backend Structure and Data Flow", "33"),
    (1, "5.4 Database Architecture & Dual-Persistence Strategy", "34"),
    (1, "5.5 Database Schema & Data Dictionaries", "35"),
    (1, "5.6 Database Schema Inspection via DB Browser for SQLite", "37"),
    (1, "5.7 API Structure & Contract Specifications", "43"),
    (1, "5.8 Authentication and Authorization", "43"),
    (1, "5.9 Security Considerations & Data Isolation", "43"),
    (1, "5.10 Data Flow Architecture (Context Diagram & Level 1 DFD)", "44"),
    (1, "5.11 Prototype / User Interface Design", "44"),
    (1, "5.12 Prototype–Architecture Mapping", "56"),
    (0, "Chapter 6 — Application Development", "57"),
    (1, "6.1 Introduction & Development Environment", "57"),
    (1, "6.2 Technology Stack Implementation Details", "57"),
    (1, "6.3 Frontend Implementation (Modular SPA Views)", "58"),
    (1, "6.4 Backend Implementation (Express REST Handlers)", "58"),
    (1, "6.5 Database Integration & Real-Time SQLite Synchronization", "58"),
    (1, "6.6 Authentication & Validation Implementation", "58"),
    (1, "6.7 Complaint Management & Geospatial Algorithms", "59"),
    (1, "6.8 Error Handling Architecture", "59"),
    (1, "6.9 Screen Walkthrough & Implemented Features", "59"),
    (1, "6.10 Key Source Code Implementation", "73"),
    (0, "Chapter 7 — Integration & System Testing", "81"),
    (1, "7.1 Introduction & Testing Objectives", "81"),
    (1, "7.2 Testing Strategy", "82"),
    (1, "7.3 Unit Testing & Mathematical Verification", "82"),
    (1, "7.4 Black-Box & System Testing", "84"),
    (1, "7.5 Integration Testing & API Verification", "83"),
    (1, "7.6 Master Software Testing Test Case Log (TC-01 to TC-52)", "85"),
    (1, "7.7 Defect & Bug Management", "91"),
    (1, "7.8 Test Execution Summary & Verification Metrics", "90"),
    (0, "Chapter 8 — Deployment", "91"),
    (1, "8.1 Introduction & Deployment Architecture", "92"),
    (1, "8.2 Local Hosting & Runtime Deployment", "92"),
    (1, "8.3 APK Build Analysis (Web-First Architectural Rationale)", "92"),
    (1, "8.4 Server Configuration & Network Topography", "92"),
    (1, "8.5 Version Control Using GitHub", "93"),
    (0, "Chapter 9 — Performance & Security Testing", "97"),
    (1, "9.1 Introduction", "97"),
    (1, "9.2 Basic Load Testing & Concurrency Analysis", "97"),
    (1, "9.3 Response Time & Latency Benchmarking", "100"),
    (1, "9.4 Input Validation Checks", "101"),
    (1, "9.5 Security Validation & Access Control", "102"),
    (1, "9.6 Identified Vulnerabilities & Implemented Resolutions", "103"),
    (1, "9.7 Performance & Security Verification Summary", "105"),
    (0, "Chapter 10 — Final Documentation", "105"),
    (1, "10.1 Project Implementation Results", "106"),
    (1, "10.2 Empirical Observations", "107"),
    (1, "10.3 Discussion of Algorithmic & Operational Results", "107"),
    (1, "10.4 System Limitations & Edge Constraints", "109"),
    (1, "10.5 Future Research & Development Scope", "109"),
    (1, "10.6 Conclusion & Achievement of Objectives", "109"),
    (0, "References", "111"),
    (0, "Appendices", "112"),
    (1, "Appendix A — Important Source Code", "112"),
    (1, "Appendix B — Additional Screenshots", "113"),
    (1, "Appendix C — Master Test Cases List", "113"),
    (1, "Appendix D — Database Structure DDL", "113"),
    (1, "Appendix E — User Manual & Operations Guide", "113"),
    (0, "Syllabus Requirements Compliance Checklist", "114"),
]

FIGURE_ITEMS = [
    ("Figure 3.1: Project Gantt Chart (Sem-V 2026-27 Milestones & Timeline)", "19"),
    ("Figure 4.1: UML Event Table — System Triggers, Sources, and Responses", "21"),
    ("Figure 4.2: UrbanClean UML Class Diagram", "22"),
    ("Figure 4.3: UrbanClean Object Diagram — Runtime Snapshot", "23"),
    ("Figure 4.4: UrbanClean Use Case Diagram — Actors, Use Cases, and System Boundary", "25"),
    ("Figure 4.5: UML Sequence Diagram — End-to-End Complaint Lifecycle", "26"),
    ("Figure 4.6: UrbanClean Component Diagram", "27"),
    ("Figure 4.7: UrbanClean Deployment Diagram", "28"),
    ("Figure 4.8: UrbanClean Activity Diagram — Complaint Processing, Routing, and Resolution Flow", "30"),
    ("Figure 5.1: High-Level Layered System Architecture of UrbanClean", "32"),
    ("Figure 5.2: UrbanClean Backend Structure and Data Flow", "34"),
    ("Figure 5.3: DB Browser for SQLite — accounts & complaints Tables", "39"),
    ("Figure 5.4: DB Browser for SQLite — driver_routes & notifications Tables", "41"),
    ("Figure 5.5: DB Browser for SQLite — drivers Fleet Roster Table", "43"),
    ("Figure 5.6: Prototype — Public Landing Page & Cleanliness Statistics", "45"),
    ("Figure 5.7: Prototype — Multi-Role Unified Authentication Portal", "46"),
    ("Figure 5.8: Prototype — Citizen Registration & Account Creation", "47"),
    ("Figure 5.9: Prototype — Citizen Waste Reporting & Incident Logging Form", "48"),
    ("Figure 5.10: Prototype — Interactive Geographic Location Selection & Map Canvas", "49"),
    ("Figure 5.11: Prototype — Citizen Real-Time Complaint Tracking & Lifecycle Dashboard", "50"),
    ("Figure 5.12: Prototype — Waste Collection Driver Duty Dashboard", "51"),
    ("Figure 5.13: Prototype — Driver TSP Route Optimization & Real-Road Navigation Map", "52"),
    ("Figure 5.14: Prototype — Proof-of-Cleanup Image Upload & Verification Interface", "53"),
    ("Figure 5.15: Prototype — Municipal Administrator Command Center & Analytics Dashboard", "54"),
    ("Figure 5.16: Prototype — City-Wide Waste Monitoring Map & GIS Filtering", "55"),
    ("Figure 5.17: Prototype — Municipal Monthly Compliance Tracking & Data Export Report", "56"),
    ("Figure 6.1: Public Landing Page, Multi-Role Login & Citizen Registration", "61"),
    ("Figure 6.2: Citizen Waste Reporting Interface & Interactive Map Pinning", "63"),
    ("Figure 6.3: GPS Geolocation Telemetry, Citizen Ticket Tracking & Driver Dashboard", "65"),
    ("Figure 6.4: Driver Optimized Route Map (5 Stops) & Proof-of-Cleanup Upload", "67"),
    ("Figure 6.5: Municipal Administrator Command Center, Active Drivers & Daily Complaints Modal", "69"),
    ("Figure 6.6: City-Wide Waste Monitoring Map & Monthly Compliance Tracking Report with Excel Export", "71"),
    ("Figure 6.7: Mobile Responsive Device View across Smartphone Viewport", "73"),
    ("Figure 7.1: Unit Testing Suite Execution Output (unit_tests.js — S23)", "82"),
    ("Figure 7.2: REST API & Component Integration Verification (integration_tests.js — S24)", "83"),
    ("Figure 7.3: Dual Persistence (db.json <-> SQLite) Sync Verification (verify_db_sync.py — S25)", "84"),
    ("Figure 8.1: GitHub Repository Remote & Branch Configuration (S44)", "94"),
    ("Figure 8.2: GitHub Project Directory Structure (git ls-tree — S45)", "95"),
    ("Figure 8.3: Source Code Tracking & Working Tree Commit Inspection (git log -n 1 --stat — S46)", "96"),
    ("Figure 8.4: Git Commit History Timeline & Provenance Audit (git log --graph --oneline — S47)", "97"),
    ("Figure 9.1: Autocannon Basic Load Testing Configuration (S37)", "98"),
    ("Figure 9.2: Autocannon Live Concurrency Load Execution Progress (S38)", "99"),
    ("Figure 9.3: Autocannon Concurrency Load Test Final Results (S39)", "100"),
    ("Figure 9.4: REST API Response Time & Latency Benchmark (benchmark_latency.js — S36)", "101"),
    ("Figure 9.5: Input Validation Failure — Duplicate Account & Password Constraints (S30)", "102"),
    ("Figure 9.6: Cryptographic Session Authentication — POST /api/login (S32)", "103"),
    ("Figure 9.7: Defect BUG-01: Raw 500 Stack Trace on Invalid File MIME Upload (S40)", "104"),
    ("Figure 9.8: Defect BUG-01 Retest: Graceful HTTP 400 Bad Request JSON Response (S41)", "105"),
]

TABLE_ITEMS = [
    ("Table 1.1: Stakeholder Identification and System Expectations", "4"),
    ("Table 2.1: Functional Requirements Specification (FR-01 to FR-28)", "7"),
    ("Table 2.2: Non-Functional Requirements Specification (NFR-01 to NFR-19)", "10"),
    ("Table 2.3: Hardware Requirements Specification", "13"),
    ("Table 2.4: Software Technology Stack Specifications", "14"),
    ("Table 3.1: Work Breakdown Structure (WBS)", "16"),
    ("Table 3.2: Project Milestone Schedule (Project Gantt Chart Sem-V 2026-27)", "17"),
    ("Table 3.3: Risk Identification, Assessment, and Mitigation Matrix", "18"),
    ("Table 5.1: Data Dictionary — accounts Table", "35"),
    ("Table 5.2: Data Dictionary — complaints Table", "36"),
    ("Table 5.3: Data Dictionary — driver_routes Table", "36"),
    ("Table 5.4: Data Dictionary — drivers Table", "37"),
    ("Table 5.5: Data Dictionary — notifications Table", "37"),
    ("Table 5.6: Prototype–Architecture Tier Mapping", "56"),
    ("Table 7.1: Master Software Testing Test Case Log (TC-01 through TC-52)", "85"),
    ("Table 7.2: Test Cases Category Breakdown and Execution Metrics", "90"),
    ("Table 10.1: Evaluated Operational Fuel Savings Across Municipal Fleets", "108"),
    ("Table 10.2: Comparison of Project Objectives with Implementation Results", "108"),
]
