# -*- coding: utf-8 -*-
"""
Structured Data with Exact Page Numbers for:
1. Table of Contents / Index
2. List of Figures
3. List of Tables
All entries have right-aligned tab stops and dot leaders.
Strictly restructured to the 10 required chapters and subtopics.
Calibrated exactly against the compiled master academic project report PDF.
"""

TOC_ITEMS = [
    # (level, title, page)
    # level 0: Major section / chapter (bold, left indent 0.0)
    # level 1: Section (regular, left indent 0.25)
    (0, "Preliminary Pages", "i"),
    (1, "Title Page", "i"),
    (1, "Certificate of Authenticity", "ii"),
    (1, "Candidate Declaration", "iii"),
    (1, "Acknowledgement", "iv"),
    (1, "Abstract", "v"),
    (1, "Table of Contents / Index", "vi"),
    (1, "List of Figures", "viii"),
    (1, "List of Tables", "ix"),
    (1, "List of Abbreviations", "x"),
    (0, "Chapter 1 — Problem Identification & Feasibility Study", "1"),
    (1, "1.1 Real-World Problem", "1"),
    (1, "1.2 Justification & Scope", "1"),
    (1, "1.3 Stakeholders", "2"),
    (1, "1.4 Feasibility: Technical, Economic, Operational", "3"),
    (0, "Chapter 2 — Requirement Engineering", "4"),
    (1, "2.1 Functional Requirements (FRs)", "4"),
    (1, "2.2 Non-Functional Requirements (NFRs)", "7"),
    (1, "2.3 Use-Case Analysis Across Actors", "9"),
    (1, "2.4 Prioritization (MoSCoW Framework)", "9"),
    (1, "2.5 Constraints and Assumptions", "10"),
    (0, "Chapter 3 — SDLC Planning", "11"),
    (1, "3.1 Selection of SDLC Model", "11"),
    (1, "3.2 Work Breakdown Structure (WBS)", "12"),
    (1, "3.3 Timeline / Gantt Chart", "13"),
    (1, "3.4 Resource Planning", "14"),
    (0, "Chapter 4 — System Modeling Using UML", "14"),
    (1, "4.1 Event Table", "14"),
    (1, "4.2 Use Case Diagram", "16"),
    (1, "4.3 Class Diagram", "17"),
    (1, "4.4 Sequence Diagram", "18"),
    (1, "4.5 Activity Diagram", "19"),
    (1, "4.6 ER Diagram", "21"),
    (1, "4.7 Deployment Diagram", "22"),
    (0, "Chapter 5 — System Architecture Design", "23"),
    (1, "5.1 Frontend Architecture — Prototype Only", "24"),
    (1, "5.2 Backend Architecture", "36"),
    (1, "5.3 Database Schema Design — Structure of Data", "38"),
    (1, "5.4 API Structure", "46"),
    (1, "5.5 Security Considerations", "46"),
    (0, "Chapter 6 — Application Development", "47"),
    (1, "6.1 Frontend Implementation", "47"),
    (1, "6.2 Backend Implementation", "61"),
    (1, "6.3 Database Integration", "61"),
    (1, "6.4 Authentication & Validation", "61"),
    (1, "6.5 Error Handling", "62"),
    (0, "Chapter 7 — Integration & System Testing", "62"),
    (1, "7.1 Unit Testing", "62"),
    (1, "7.2 Black-Box Testing", "63"),
    (1, "7.3 Integration Testing", "64"),
    (1, "7.4 Test Case Preparation", "65"),
    (1, "7.5 Bug Tracking", "70"),
    (0, "Chapter 8 — Deployment", "71"),
    (1, "8.1 Cloud Deployment / Local Hosting", "71"),
    (1, "8.2 APK Build", "71"),
    (1, "8.3 Server Configuration", "72"),
    (1, "8.4 Version Control Using GitHub", "72"),
    (0, "Chapter 9 — Performance & Security Testing", "76"),
    (1, "9.1 Basic Load Testing", "76"),
    (1, "9.2 Input Validation Checks", "80"),
    (1, "9.3 Security Validation", "81"),
    (0, "Chapter 10 — Result and Discussion", "84"),
    (1, "10.1 Technical Report", "84"),
    (1, "10.2 User Manual", "85"),
    (1, "10.3 Screenshots", "86"),
    (1, "10.4 Source Code Documentation", "87"),
]

FIGURE_ITEMS = [
    ("Figure 3.1: Project Gantt Chart (Sem-V 2026-27 Milestones & Timeline)", "13"),
    ("Figure 4.1: UML Event Table — System Triggers, Sources, and Responses", "15"),
    ("Figure 4.2: UrbanClean Use Case Diagram — Actors, Use Cases, and System Boundary", "16"),
    ("Figure 4.3: UrbanClean UML Class Diagram", "17"),
    ("Figure 4.4: UML Sequence Diagram — End-to-End Complaint Lifecycle", "18"),
    ("Figure 4.5: UrbanClean Activity Diagram — Complaint Processing, Routing, and Resolution Flow", "20"),
    ("Figure 4.6: Entity-Relationship Diagram of UrbanClean", "21"),
    ("Figure 4.7: UrbanClean Deployment Diagram", "23"),
    ("Figure 5.1: Prototype — Public Landing Page & Cleanliness Statistics", "24"),
    ("Figure 5.2: Prototype — Multi-Role Unified Authentication Portal", "25"),
    ("Figure 5.3: Prototype — Citizen Registration & Account Creation", "26"),
    ("Figure 5.4: Prototype — Citizen Waste Reporting & Incident Logging Form", "27"),
    ("Figure 5.5: Prototype — Interactive Geographic Location Selection & Map Canvas", "28"),
    ("Figure 5.6: Prototype — Citizen Real-Time Complaint Tracking & Lifecycle Dashboard", "29"),
    ("Figure 5.7: Prototype — Waste Collection Driver Duty Dashboard", "30"),
    ("Figure 5.8: Prototype — Driver TSP Route Optimization & Real-Road Navigation Map", "31"),
    ("Figure 5.9: Prototype — Proof-of-Cleanup Image Upload & Verification Interface", "32"),
    ("Figure 5.10: Prototype — Municipal Administrator Command Center & Analytics Dashboard", "33"),
    ("Figure 5.11: Prototype — City-Wide Waste Monitoring Map & GIS Filtering", "34"),
    ("Figure 5.12: Prototype — Municipal Monthly Compliance Tracking & Data Export Report", "35"),
    ("Figure 5.13: UrbanClean Backend Structure and Data Flow", "36"),
    ("Figure 5.14: DB Browser for SQLite — accounts & complaints Tables", "42"),
    ("Figure 5.15: DB Browser for SQLite — driver_routes & notifications Tables", "44"),
    ("Figure 5.16: DB Browser for SQLite — drivers Fleet Roster Table", "46"),
    ("Figure 6.1: Public Landing Page, Multi-Role Login & Citizen Registration", "49"),
    ("Figure 6.2: Citizen Waste Reporting Interface & Interactive Map Pinning", "51"),
    ("Figure 6.3: GPS Geolocation Telemetry, Citizen Ticket Tracking & Driver Dashboard", "53"),
    ("Figure 6.4: Driver Optimized Route Map (5 Stops) & Proof-of-Cleanup Upload", "55"),
    ("Figure 6.5: Municipal Administrator Command Center, Active Drivers & Daily Complaints Modal", "57"),
    ("Figure 6.6: City-Wide Waste Monitoring Map & Monthly Compliance Tracking Report with Excel Export", "59"),
    ("Figure 6.7: Mobile Responsive Device View across Smartphone Viewport", "61"),
    ("Figure 7.1: Unit Testing Suite Execution Output (unit_tests.js — S23)", "63"),
    ("Figure 7.2: REST API & Component Integration Verification (integration_tests.js — S24)", "64"),
    ("Figure 7.3: Dual Persistence (db.json <-> SQLite) Sync Verification (verify_db_sync.py — S25)", "65"),
    ("Figure 8.1: GitHub Repository Remote & Branch Configuration (S44)", "73"),
    ("Figure 8.2: GitHub Project Directory Structure (git ls-tree — S45)", "74"),
    ("Figure 8.3: Source Code Tracking & Working Tree Commit Inspection (git log -n 1 --stat — S46)", "75"),
    ("Figure 8.4: Git Commit History Timeline & Provenance Audit (git log --graph --oneline — S47)", "76"),
    ("Figure 9.1: Autocannon Basic Load Testing Configuration (S37)", "77"),
    ("Figure 9.2: Autocannon Live Concurrency Load Execution Progress (S38)", "78"),
    ("Figure 9.3: Autocannon Concurrency Load Test Final Results (S39)", "79"),
    ("Figure 9.4: REST API Response Time & Latency Benchmark (benchmark_latency.js — S36)", "80"),
    ("Figure 9.5: Input Validation Failure — Duplicate Account & Password Constraints (S30)", "81"),
    ("Figure 9.6: Cryptographic Session Authentication — POST /api/login (S32)", "82"),
    ("Figure 9.7: Defect BUG-01: Raw 500 Stack Trace on Invalid File MIME Upload (S40)", "83"),
    ("Figure 9.8: Defect BUG-01 Retest: Graceful HTTP 400 Bad Request JSON Response (S41)", "84"),
]

TABLE_ITEMS = [
    ("Table 1.1: Stakeholder Identification and System Expectations", "2"),
    ("Table 2.1: Functional Requirements Specification (FR-01 to FR-28)", "4"),
    ("Table 2.2: Non-Functional Requirements Specification (NFR-01 to NFR-19)", "7"),
    ("Table 2.3: Hardware Requirements Specification", "10"),
    ("Table 2.4: Software Technology Stack Specifications", "11"),
    ("Table 3.1: Work Breakdown Structure (WBS)", "12"),
    ("Table 3.2: Project Milestone Schedule (Project Gantt Chart Sem-V 2026-27)", "13"),
    ("Table 5.1: Prototype–Architecture Tier Mapping", "35"),
    ("Table 5.2: Data Dictionary — accounts Table", "38"),
    ("Table 5.3: Data Dictionary — complaints Table", "38"),
    ("Table 5.4: Data Dictionary — driver_routes Table", "39"),
    ("Table 5.5: Data Dictionary — drivers Table", "39"),
    ("Table 5.6: Data Dictionary — notifications Table", "40"),
    ("Table 7.1: Master Software Testing Test Case Log (TC-01 through TC-52)", "65"),
    ("Table 7.2: Test Cases Category Breakdown and Execution Metrics", "70"),
    ("Table 10.1: Evaluated Operational Fuel Savings Across Municipal Fleets", "84"),
    ("Table 10.2: Comparison of Project Objectives with Implementation Results", "85"),
]
